// Mocks generated by Mockito 5.4.6 from annotations
// in anime_title_academy/test/features/title_academy/quota_gated_pipeline_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:anime_title_academy/core/ads/ad_reward_result.dart' as _i4;
import 'package:anime_title_academy/core/ads/ad_runtime_mode.dart' as _i9;
import 'package:anime_title_academy/core/ads/ad_service.dart' as _i8;
import 'package:anime_title_academy/features/title_academy/domain/quota_consume_result.dart'
    as _i3;
import 'package:anime_title_academy/features/title_academy/domain/title_generation_model.dart'
    as _i7;
import 'package:anime_title_academy/features/title_academy/domain/title_usage_quota_service.dart'
    as _i5;
import 'package:anime_title_academy/features/title_academy/domain/title_usage_quota_snapshot.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTitleUsageQuotaSnapshot_0 extends _i1.SmartFake
    implements _i2.TitleUsageQuotaSnapshot {
  _FakeTitleUsageQuotaSnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuotaConsumeResult_1 extends _i1.SmartFake
    implements _i3.QuotaConsumeResult {
  _FakeQuotaConsumeResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdRewardResult_2 extends _i1.SmartFake
    implements _i4.AdRewardResult {
  _FakeAdRewardResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TitleUsageQuotaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTitleUsageQuotaService extends _i1.Mock
    implements _i5.TitleUsageQuotaService {
  @override
  _i6.Future<_i2.TitleUsageQuotaSnapshot> getQuota() =>
      (super.noSuchMethod(
            Invocation.method(#getQuota, []),
            returnValue: _i6.Future<_i2.TitleUsageQuotaSnapshot>.value(
              _FakeTitleUsageQuotaSnapshot_0(
                this,
                Invocation.method(#getQuota, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.TitleUsageQuotaSnapshot>.value(
                  _FakeTitleUsageQuotaSnapshot_0(
                    this,
                    Invocation.method(#getQuota, []),
                  ),
                ),
          )
          as _i6.Future<_i2.TitleUsageQuotaSnapshot>);

  @override
  _i6.Future<_i3.QuotaConsumeResult> consume(_i7.TitleGenerationModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#consume, [model]),
            returnValue: _i6.Future<_i3.QuotaConsumeResult>.value(
              _FakeQuotaConsumeResult_1(
                this,
                Invocation.method(#consume, [model]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.QuotaConsumeResult>.value(
              _FakeQuotaConsumeResult_1(
                this,
                Invocation.method(#consume, [model]),
              ),
            ),
          )
          as _i6.Future<_i3.QuotaConsumeResult>);

  @override
  _i6.Future<_i2.TitleUsageQuotaSnapshot> reward(
    _i7.TitleGenerationModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reward, [model]),
            returnValue: _i6.Future<_i2.TitleUsageQuotaSnapshot>.value(
              _FakeTitleUsageQuotaSnapshot_0(
                this,
                Invocation.method(#reward, [model]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.TitleUsageQuotaSnapshot>.value(
                  _FakeTitleUsageQuotaSnapshot_0(
                    this,
                    Invocation.method(#reward, [model]),
                  ),
                ),
          )
          as _i6.Future<_i2.TitleUsageQuotaSnapshot>);
}

/// A class which mocks [AdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdService extends _i1.Mock implements _i8.AdService {
  @override
  _i9.RewardedAdMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i9.RewardedAdMode.disabled,
            returnValueForMissingStub: _i9.RewardedAdMode.disabled,
          )
          as _i9.RewardedAdMode);

  @override
  _i6.Future<_i4.AdRewardResult> showRewardedAd({
    required _i7.TitleGenerationModel? model,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showRewardedAd, [], {#model: model}),
            returnValue: _i6.Future<_i4.AdRewardResult>.value(
              _FakeAdRewardResult_2(
                this,
                Invocation.method(#showRewardedAd, [], {#model: model}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.AdRewardResult>.value(
              _FakeAdRewardResult_2(
                this,
                Invocation.method(#showRewardedAd, [], {#model: model}),
              ),
            ),
          )
          as _i6.Future<_i4.AdRewardResult>);
}
